-- MySQL Script generated by MySQL Workbench
-- Min 14 Agu 2022 06:19:37 
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema e_voting
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `e_voting` ;

-- -----------------------------------------------------
-- Schema e_voting
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `e_voting` DEFAULT CHARACTER SET utf8 ;
USE `e_voting` ;

-- -----------------------------------------------------
-- Table `e_voting`.`Voter`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `e_voting`.`Voter` ;

CREATE TABLE IF NOT EXISTS `e_voting`.`Voter` (
  `NIM` VARCHAR(10) NOT NULL,
  `nama` VARCHAR(225) NOT NULL,
  `has_been` ENUM('Y', 'N') NOT NULL,
  PRIMARY KEY (`NIM`),
  UNIQUE INDEX `NIM_UNIQUE` (`NIM` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e_voting`.`Vote`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `e_voting`.`Vote` ;

CREATE TABLE IF NOT EXISTS `e_voting`.`Vote` (
  `voter` VARCHAR(10) NOT NULL,
  `candidate` VARCHAR(10) NOT NULL,
  `timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX `fk_Vote_Voter1_idx` (`voter` ASC),
  PRIMARY KEY (`voter`),
  UNIQUE INDEX `from_UNIQUE` (`voter` ASC),
  INDEX `fk_Vote_Voter2_idx` (`candidate` ASC),
  CONSTRAINT `fk_Vote_Voter1`
    FOREIGN KEY (`voter`)
    REFERENCES `e_voting`.`Voter` (`NIM`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vote_Voter2`
    FOREIGN KEY (`candidate`)
    REFERENCES `e_voting`.`Voter` (`NIM`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `e_voting` ;

-- -----------------------------------------------------
-- Placeholder table for view `e_voting`.`not_yet_voted`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e_voting`.`not_yet_voted` (`NIM` INT);

-- -----------------------------------------------------
-- Placeholder table for view `e_voting`.`candidate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e_voting`.`candidate` (`NIM` INT, `nama` INT);

-- -----------------------------------------------------
-- View `e_voting`.`not_yet_voted`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `e_voting`.`not_yet_voted`;
DROP VIEW IF EXISTS `e_voting`.`not_yet_voted` ;
USE `e_voting`;
CREATE  OR REPLACE VIEW `not_yet_voted` AS
	SELECT Voter.NIM FROM Voter LEFT JOIN Vote
    ON Voter.NIM = Vote.Voter WHERE Vote.Voter IS NULL;

-- -----------------------------------------------------
-- View `e_voting`.`candidate`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `e_voting`.`candidate`;
DROP VIEW IF EXISTS `e_voting`.`candidate` ;
USE `e_voting`;
CREATE  OR REPLACE VIEW `candidate` AS
	SELECT NIM, nama FROM Voter WHERE has_been = 'N';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
